### ISSUE TITLE
Import Latest NTPSec Release

### ISSUE THREAD

**Issue by RainbowHackerHorse** [PurLinux/Base#3]
NTPSec reached a stable release. Import to Base.

**Comment by ghost** [comment]
done in (yet to be merged in) changes.

some notes:
- it requires python as a build dep. i compile it, install it, and then remove it (...by hand. since python's makefile doesn't include an uninstall, which is kind of bullshit if you ask me.)
- it requires libevent2 as a build AND runtime dep. this is also incorporated.
